services:
  postgres:
    image: postgres:latest
    container_name: drizzle-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
volumes:
  postgres_data: